# Generated by Django 3.0.4 on 2020-03-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_id', models.CharField(max_length=3)),
                ('pass_no', models.CharField(max_length=3)),
            ],
        ),
    ]
